// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcOE5Js7rZTrzj0aiHxDrxwx9dQ5GmJ4',
    appId: '1:461123565952:web:d109094d86935a4404e965',
    messagingSenderId: '461123565952',
    projectId: 'hellofirebase-715a4',
    authDomain: 'hellofirebase-715a4.firebaseapp.com',
    storageBucket: 'hellofirebase-715a4.appspot.com',
    measurementId: 'G-4CPMSJ6GQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBgK4k8XcdsN4aUdkR8cZ3_2tUKgMgkEw',
    appId: '1:461123565952:android:5001b4304dee93a004e965',
    messagingSenderId: '461123565952',
    projectId: 'hellofirebase-715a4',
    storageBucket: 'hellofirebase-715a4.appspot.com',
  );
}
